### ISSUE TITLE
Use a pronounceable name?  How about wurl?

### ISSUE THREAD

**Issue by jas4711** [curl/wcurl#12]
Thanks for this project, I can sympathize with the rationale because I never managed to learn the syntax to make curl do what wget does either.   The name is really hard to pronounce though, and command line completion is stuck on the well-know Unix tool `wc`.  Did you consider renaming this to something else?  How about `wurl`?  The two-letter prefix `wu` doesn't complete to anything on my machine, so presumably no too common Unix tool clashes.

I'm sure you already thought about this, but I didn't see a issue about it for having a public discussion on it, so here is :)

**Comment by ilyagr** [comment]
While I'm not in a position of responsibility here, I like the `wcurl` name, it makes it pretty clear what the tool is.

I would pronounce `wcurl` as `double-you curl`, and `wget` as `double-you get`, so to me their pronunciation is equivalent in difficulty. How would you pronounce `wget`?

Furthermore, I found `wurl` more difficult to pronounce, or at least more awkward-sounding. Is it like `whirl`, but `whurl`?

**Comment by BrianInglis** [comment]
Sounds like *wh[aeiou]rl*: fudge the vowel depending on accent - give it a `wurl`; take it for a `wurl`; like how that sounds `;^>` *++*

**Comment by samueloph** [comment]
I'm afraid it became too late to change the name, but I'm also not sure there's a better alternative.

I acknowledge the issue with CLI completion and the clash with `wc`, but I like more the upside of having a clear name such as `wcurl`. Having `curl` in the name makes it clear this is just curl, with a wrapper on top.

Regarding the pronunciation, none of the alternatives are easier to pronounce for me: wurl, whirl, whurl... are all things that I would struggle much more rather than `wcurl`.

This being said, how easy it is to pronounce will depend on your native language, so it is a bit subjective after all.

A couple of weeks ago someone pointed out that I always pronounce the `w` in `wcurl` in Brazilian Portuguese rather than English, maybe that's a reason I find it easier to pronounce it?! The Brazilian pronunciation of `w` is close enough to the English one such that everybody still understands it.

**Comment by sergiodj** [comment]
Agreed with @samueloph here.  That ship has sailed :-).  Also, `wurl` is very hard to pronounce! :D
