### ISSUE TITLE
tests/test.sh sources . shunit2 presumably to run tests but shunit2 is not provided

### ISSUE THREAD

**Issue by BrianInglis** [curl/wcurl#22]
`tests/test.sh` defines a bunch of functions with test cases, but never runs them. 
At the end it sources `. shunit2` presumably to run tests?
But `shunit2` is not provided in the repo.

**Comment by sergiodj** [comment]
Hi,

Thanks for reporting a bug.

`shunit2` isn't provided because it's supposed to be installed by the developer.  If you're running Debian or some derivative of it, you can install it by doing `apt install shunit2`.

Granted, we could improve the documentation and explain how to install the required dependencies, but IMO that should be tracked in another bug.  Closing this one appropriately.

Cheers.
