### ISSUE TITLE
Keeping README.md and wcurl.1 in sync

### ISSUE THREAD

**Issue by ryandesign** [curl/wcurl#7]
When I initially submitted https://salsa.debian.org/debian/wcurl/-/merge_requests/3 to fix a problem in wcurl.1 I had not realized that the contents of wcurl.1 were incorporated into README.md. I later corrected it by adding the same change to README.md.

The same problem happened in e4a7f678f4b9ba473fc51b51c2f0e02c74134d3c and has not yet been corrected. The changes made to wcurl.1 in that commit have yet to be made to README.md.

Having to make changes to both files independently leads to the files getting out of sync. What is the intended method by which they should remain in sync? Is there a script that formats wcurl.1 into Markdown and replaces what's in README.md? If so could that script be added to the repo, and could documentation covering this and any other developer-specific topics be added to the repo?

**Comment by samueloph** [comment]
> Having to make changes to both files independently leads to the files getting out of sync.

Yeah, maybe that wasn't a good idea.

> What is the intended method by which they should remain in sync? Is there a script that formats wcurl.1 into Markdown and replaces what's in README.md? If so could that script be added to the repo, and could documentation covering this and any other developer-specific topics be added to the repo?

I've used https://github.com/mle86/man-to-md to convert it, but had to manually change a few things.

I'll leave this open until the process is documented (or we change what's on README.md).

Thank you for reporting!

**Comment by gnomon-** [comment]
In case it helps, this might not be a problem that needs to be solved.  A `README.md` file is an introduction to a codebase and addresses topics to people approaching the project from that direction, and works best when it describes the purpose of the tool and then covers topics like how to compile, install, and configure it, how to contribute to the project, and so on; whereas a man page is a brief reference [with a structured format](https://manpages.debian.org/bookworm/man-db/man.1.en.html) intended to guide a user through invoking, using, configuring, and understanding the runtime behavior of the tool.

Since `wcurl` is still quite young it makes sense that the `README.md` file and the man page are almost identical, but it's reasonable to expect the files to diverge more and more over time.  The sync problem might disappear naturally without requiring a technical solution.

**Comment by samueloph** [comment]
At this points is safe to assume the README and manpage will purposely diverge further (README has a logo now).

It's also safe to assume the manpage will only receive minor updates, since we don't expect any big changes, the biggest one would be https://salsa.debian.org/debian/wcurl/-/merge_requests/4.

I'll close this issue for now.
